version: '3'

services:
  elasticsearch:
    container_name: elasticsearch
    hostname: elasticsearch
    #    image: my-es
    build:
     context: .
     dockerfile: Dockerfile
    ports:
     - 9200:9200
     - 9300:9300
    volumes:
     - ./data:/usr/share/elasticsearch/data
     - ./logs:/usr/share/elasticsearch/logs
       #     - ./plugins:/usr/share/elasticsearch/plugins
     - ./conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    environment:
     - network.host=0.0.0.0
     - discovery.type=single-node
     - "path.repo=/usr/share/elasticsearch/data/search_example"
     - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
     - node.max_local_storage_nodes=2
     - TZ=Asia/Seoul
#   user: root
    networks:
     - es

  kibana:
    container_name: kibana
    hostname: kibana
    image: kibana:7.9.1
    ports:
     - 5601:5601
    volumes:
     - ./conf/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    depends_on:
     - elasticsearch
    networks:
     - es

networks:
 es:
   external: true
